use_default_settings: true

general:
  instance_name: "YouTube Research SearXNG"

search:
  safe_search: 0
  formats:
    - html
    - json

server:
  secret_key: "2fbdd897a3900e5328d943c4115f4bc6d1c652c4943e16bb499d6e58a876eca8"
  limiter: false
  image_proxy: false